### PR TITLE
cleanup R_t varnames

### PR DESCRIPTION
**Pull request by exaexa**
cc @AtteAalto 

(
Includes an algebra shortcut with week dates.

I'm not sure about commit 6aec58871808b3dbd54133b45298e8b661b1d6b5 though -- the computation before it should be moreless the same as with your commit, but seemed to me like it was counting weeks from tuesday to monday. Better ask. :D
)

### CODE REVIEW

**Review by laurentheirendt — COMMENTED** [review]
I guess @AtteAalto or @daniele-proverbio is better suited to review this

**Comment by daniele-proverbio** [comment]
@AtteAalto for sure ;)

**Comment by exaexa** [comment]
I can't add Atte to the reviewer list though :(

**Comment by AtteAalto** [comment]
Yes, I think the weeks are now defined from Tuesday to Monday, since I've looked at the reporting days. I agree that using the case dates is more logical, so you can change that. It will of course have a minor effect on the results, but to me that's fine.

**Pull request merged**
